ShopAdvisor/Controllers/PlacesController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using DataShopAdvisor;
using DataShopAdvisor.Modelos;
using BIShopAdvisor;
using EntidadesShopAdvisor;
using System.Collections.Generic;
using System.Linq;
using System;

namespace ShopAdvisor.Controllers
{
    public class PlacesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Places
        public async Task<ActionResult> Index()
        {
            if (Request.IsAjaxRequest())
            {
                 return Json(await new BIPlace().GetAll(),
                     JsonRequestBehavior.AllowGet);
            }
            else
                return View(await new BIPlace().GetAll());
        }

        // GET: Places/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlaceComments oPlaceComments = new PlaceComments();
            Place place = await db.Places.FindAsync(id);
            IEnumerable<Comment> comments = await db.Comments.Where(x=>x.place.id==id).ToListAsync();
            oPlaceComments.Place = place;
            oPlaceComments.Comments = comments;
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(oPlaceComments);
        }

        // GET: Places/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Places/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,name,latitud,longitud")]
        Place place, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var filename = image.FileName;
                var filePathOriginal = Server.MapPath("/content/uploads/places");
                string savedFileName = Path.Combine(filePathOriginal, filename);
                place.image_path = @"/content/uploads/places/" + filename;
                db.Places.Add(place);
                await db.SaveChangesAsync();                
                image.SaveAs(savedFileName);
                return RedirectToAction("Index");
            }

            return View(place);
        }

        // GET: Places/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = await db.Places.FindAsync(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,name,latitud,longitud")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Entry(place).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(place);
        }

        // GET: Places/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = await db.Places.FindAsync(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Place place = await db.Places.FindAsync(id);
            db.Places.Remove(place);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        [HttpPost, ActionName("CreateCommentPlace")]
        public async Task<ActionResult> CreateCommentPlace(FormCollection data)
        {
            Comment oComment = new Comment();
            oComment.comment = data["comment"];
            Place oPlace = await db.Places.FindAsync(Convert.ToInt32(data["place"]));
            oComment.place = oPlace;
            db.Comments.Add(oComment);
            await db.SaveChangesAsync();
            IEnumerable<Comment> comments = await db.Comments.Where(x => x.place.id == oComment.place.id).ToListAsync();
            PlaceComments oPlaceComments = new PlaceComments();
            oPlaceComments.Place = oPlace;
            oPlaceComments.Comments = comments;
            return PartialView("PartialViewComment", oPlaceComments);
        }

        [HttpPost, ActionName("DeleteCommentPlace")]
        public async Task<ActionResult> DeleteCommentPlace(int place, int comment)
        {
            Comment oComment = await db.Comments.FindAsync(comment);
            db.Comments.Remove(oComment);
            await db.SaveChangesAsync();
            PlaceComments oPlaceComments = new PlaceComments();
            Place oPlace = await db.Places.FindAsync(place);
            IEnumerable<Comment> comments = await db.Comments.Where(x => x.place.id == place).ToListAsync();
            oPlaceComments.Place = oPlace;
            oPlaceComments.Comments = comments;
            return PartialView("PartialViewComment", oPlaceComments);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopAdvisor/Views/Shared/PartialViewComment.cshtml
@model EntidadesShopAdvisor.PlaceComments

<table class="table">
    <tr>
        <th>
            Comentarios
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Comments)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.comment)
            </td>
            <td>
                @Ajax.ActionLink("Delete", "DeleteCommentPlace", "Places", new
               {
                   place = Model.Place.id,
                   comment = item.id,
               },
                    new AjaxOptions
                    {
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "contenido",
                        AllowCache=false
                    })
            </td>
        </tr>
    }

</table>

ShopAdvisor/Views/Shared/PartialViewPlace.cshtml
@model IEnumerable<DataShopAdvisor.Modelos.Place>

<div class="gradient">
    @foreach (var item in Model)
    {

        <div class="wrap">
            <div class="card">
                <a href="@Url.Action("Details", "Places",new {id=item.id })">
                    <div class="price">@item.id<span class="glyphicon glyphicon-eur" aria-hidden="true"></span>  / Identificador</div>
                    <div class="image"><img src="@item.image_path" /> </div>
                    <div class="description">
                        <div class="row">
                            <div class="col-sm-3"><h4>@Html.DisplayFor(modelItem => item.name)</h4></div>
                            <div class="col-sm-9">
                                <ul>
                                    <li><span class="glyphicon glyphicon-user" aria-hidden="true"><p>@Html.DisplayFor(modelItem => item.latitud)</p></li>
                                    <li><span class="glyphicon glyphicon-signal" aria-hidden="true"><p>@Html.DisplayFor(modelItem => item.longitud)</p></li>
                                    <li>
                                        <a href="@Url.Action("Delete", "Place",new {id=item.id })">
                                            <span class="glyphicon glyphicon-erase" aria-hidden="true"><p>Eliminar</p></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

        </div>




        @*<div class="gradient">
                <div class="wrap">
                    <div class="card">
                        <a href="http://tornadostudio.si/vila">
                            <div class="price">60<span class="glyphicon glyphicon-eur" aria-hidden="true"></span>  / day</div>
                            <div class="image"></div>
                            <div class="description">
                                <div class="row">
                                    <div class="col-sm-3"><h4>Vila Golf</h4></div>
                                    <div class="col-sm-9">
                                        <ul>
                                            <li><span class="glyphicon glyphicon-user" aria-hidden="true"><p>3 persons</p></li>
                                            <li><span class="glyphicon glyphicon-signal" aria-hidden="true"><p>Free WI-FI</p></li>
                                            <li><span class="glyphicon glyphicon-cutlery" aria-hidden="true"><p>Kitchen</p></li>
                                            <li><span class="glyphicon glyphicon-tint" aria-hidden="true"><p>Bathroom</p></li>
                                        </ul>
                                    </div>
                                </div>

                            </div>
                        </a>
                    </div>
                </div>
            </div>*@
    }
</div>

ShopAdvisor/Views/Shared/_Layout.cshtml
@using HtmlExtension

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
    @Styles.Render("~/Content/css")

    <script type="text/javascript">

        var operacion = 0;
        var suma = 0;
        if (operacion == 0) {
            suma = 1 + 1;
            console.log(suma);
            //alert(suma);
        }

    </script>

</head>
<body>

        <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Shop Advisor
                    </a>
                </li>
                <li>
                    @Html.ActionLink("Inicio", "Index", "Home",new { id = "inicio" })
                </li>
                <li>
                    @Html.ActionLink("Lugares", "Index", "Places")
                </li>
                <li>
                    @Html.ActionLink("Acerca de", "About", "Home")
                </li>
                <li>
                    @Html.ActionLink("Contacto", "Contact", "Home")
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="span12">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>

   
    <!-- /#wrapper -->

    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>
    *@
    @Scripts.Render("~/bundles/jquery")
    
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/sitio")

    @Scripts.Render("~/bundles/jqueryval")

    @RenderSection("scripts", required: false)

</body>
</html>