ShopAdvisor/Controllers/LINQController.cs
using DataShopAdvisor;
using DataShopAdvisor.Modelos;
using EntidadesShopAdvisor;
using ShopAdvisor.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ShopAdvisor.Controllers
{
    public class LINQController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: LINQ
        public async Task<ActionResult> Where()
        {
            var query = await db.Places.Where(item => item.latitud > 0).ToListAsync();

            return View(query);
        }

        // GET: Join
        public async Task<ActionResult> Join()
        {
            var query =
                await
               (from place in db.Places
               join comment in db.Comments
               on place.id equals comment.place.id
               select place).Where(x=>x.longitud>0).ToListAsync();

            return View(query);
        }

        // GET: Join
        public async Task<ActionResult> OrderBy(int id)
        {
            int orderBy = 0;
            var query = new List<Place>();
            if (id == 1)
            {
                query = await db.Places.OrderBy(x=>x.name).ToListAsync();
            }
            else
            {
                query = await db.Places.OrderByDescending(x => x.name).ToListAsync();

            } 
            return View(query);
        }

        // GET: Join
        public async Task<ActionResult> Admin()
        {
            var promedio= await db.Places.AverageAsync(x=>x.id);
            var contador = await db.Places.CountAsync();
            var max = await db.Places.MaxAsync(x=>x.id);
            var min = await db.Places.MinAsync(x => x.id);
            var sum = await db.Places.SumAsync(x=>x.id);

            Admin oAdmin = new Admin();
            oAdmin.Promedio = promedio;
            oAdmin.Contador = contador;
            oAdmin.Max = max;
            oAdmin.Min = min;
            oAdmin.Sum = sum;

            return View(oAdmin);
        }

        // GET: Join
        public async Task<ActionResult> Partition()
        {
            var skip = await db.Places.OrderBy(x => x.id).Skip(1).ToListAsync();
            var take = await db.Places.OrderBy(x => x.id).Take(2).ToListAsync();
          //  var skipWhile = await db.Places.SkipWhile(x => x.longitud>0).ToListAsync();
          //  var takeWhile = await db.Places.TakeWhile(x => x.longitud > 0).ToListAsync();

            Partition oPartition = new Partition();
            oPartition.Skip = skip;
            oPartition.Take = take;
            oPartition.SkipWhile = new List<Place>();
            oPartition.TakeWhile = new List<Place>();

            return View(oPartition);
        }
        
    }
}

ShopAdvisor/Views/LINQ/Admin.cshtml
@model ShopAdvisor.Entities.Admin


@{
    ViewBag.Title = "Admin";
}

<h2>Admin</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Promedio)
        </th>
        <th>
            @Html.DisplayFor(model => model.Promedio)
        </th>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Contador)
        </th>
        <th>
            @Html.DisplayFor(model => model.Contador)
        </th>
    </tr>

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Max)
        </th>
        <th>
            @Html.DisplayFor(model => model.Max)
        </th>
    </tr>

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Min)
        </th>
        <th>
            @Html.DisplayFor(model => model.Min)
        </th>
    </tr>

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Sum)
        </th>
        <th>
            @Html.DisplayFor(model => model.Sum)
        </th>
    </tr>

</table>

ShopAdvisor/Views/LINQ/Join.cshtml
@model IEnumerable<ShopAdvisor.Models.Place>

@{
    ViewBag.Title = "Join";
}

<h2>Join</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.latitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.longitud)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.latitud)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.longitud)
            </td>
        </tr>
    }
</table>

ShopAdvisor/Views/LINQ/OrderBy.cshtml
@model IEnumerable<ShopAdvisor.Models.Place>

@{
    ViewBag.Title = "Order";
}

<h2>Order</h2>

<button type="button" class="btn btn-primary"
        onclick="location.href='@Url.Action("Orderby","LINQ",new {id=1 })'"
        
        
        >Asc</button>
<button type="button" class="btn btn-success" 
        onclick="location.href='@Url.Action("Orderby","LINQ",new {id=2 })'"
        >Desc</button>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.latitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.longitud)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.latitud)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.longitud)
            </td>
        </tr>
    }
</table>

ShopAdvisor/Views/LINQ/Partition.cshtml
@model ShopAdvisor.Entities.Partition
@{
    ViewBag.Title = "Partition";
}

<h2>Partition</h2>

<h3>Skip</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Skip.First().id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Skip.First().name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Skip.First().latitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Skip.First().longitud)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Skip)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.latitud)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.longitud)
            </td>
        </tr>
    }
</table>

ShopAdvisor/Views/LINQ/Where.cshtml
@model IEnumerable<ShopAdvisor.Models.Place>

@{
    ViewBag.Title = "Where";
}

<h2>Where</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.latitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.longitud)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.latitud)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.longitud)
            </td>
        </tr>
    }
</table>